---
- hosts: all
  remote_user: atb
  # remote_password: Password#1
  tasks:
  - name: list docker packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - docker
      - docker-compose  
