---
- hosts: "10.237.198.154"
  #remote_user: root
  # remote_password: Password#1
  tasks:
  - name: list docker packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - docker
      - docker-compose  
